AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
